// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginType } from "./PluginType";

export interface PluginConfig { name: string, description: string | null, version: string, author: string | null, repository: string | null, uuid: string, type: PluginType, }