// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeColours } from "./ThemeColours";
import type { ThemeType } from "./ThemeType";

export interface EDTRTheme { name: string, type: ThemeType, colours: ThemeColours, }